server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060


logging:
  level:
    org.springframework.web: ERROR
    net.consensys: INFO
    net.consensys.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

ethereum:
  nodes:
    - name: default
      url: ws://34.197.91.149:8546
      blockStrategy: PUBSUB
      syncingThreshold: 100
      healthcheckInterval: 3000
  healthcheck:
    pollInterval: 2000
  blockStrategy: PUBSUB

ether:
  node:
    url: http://34.197.91.149:8545

contracts:
  database:
    wallet:
      ID: "Wallets"
    token:
      ID: "Tokens"
    account:
      ID: "Accounts"

pusher:
  url: http://10.10.2.5:8081/connector-pusher/rest/pusher/api/v1

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event
  latestBlockPath: /latestblock

database:
  type: MONGO

broadcaster:
  type: KAFKA
  cache:
    expirationMillis: 6000000
  event:
    confirmation:
      numBlocksToWait: 1
      numBlocksToWaitForMissingTx: 100
      numBlocksToWaitBeforeInvalidating: 2
  multiInstance: false
  enableBlockNotifications: true

# For Kafka
zookeeper:
  address: 34.197.91.149:2181
kafka:
  bootstrap:
    addresses: 34.197.91.149:9092
  topic:
    contractEvents: contract-events
    blockEvents: block-events
    eventeumEvents: eventeum-events
    transactionEvents: transaction-events

    partitions: 1
    replicationSets: 1

management:
  endpoints:
    web.base-path: /monitoring
    enabled-by-default: false
    web.exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: false


cws:
  hostname: test
  coin: teth